### ISSUE TITLE
var  a = 1; var ﾠ1 = a; var ﾠ2 = a; var ﾠ3 = a;  行不通，数字不能作为变量命名的开头

### ISSUE THREAD

**Issue by zaqwsxcderfvtgb** [HCThink/h-blog#6]
**Describe the bug**
var  a = 1;
var ﾠ1 = a;
var ﾠ2 = a;
var ﾠ3 = a;

**To Reproduce**
这个方式有问题

**Comment by hooper-hc** [comment]
非常感谢阅读和 提的 ISSUE

你是在电脑上看的么？ 为何 copy 出来在 console.log 中试一试？ 

![image](https://user-images.githubusercontent.com/11420374/49914460-50f7ca00-fecc-11e8-8f31-bc80c7085119.png)

**Comment by hooper-hc** [comment]
@zaqwsxcderfvtgb 非常感谢阅读和提的 ISSUE，这些对我意义重大！

---

你得复制上面的代码到 console 中执行， 上述的变量经过特殊处理。

这个问题和 文章中提到的

 - amazed 最让我吃惊的方案
```js
var aﾠ = 1;
var a = 2;
var ﾠa = 3;
if(aﾠ ==1 && a == 2 && ﾠa ==3) {
    console.log("Why hello there!")
}
```

原理一样， 其中的三个 a 不是同一个字符

这里的 var ﾠ1 = a; 中的  ﾠ1  并不是数组，他前面有个别的字符集，渲染不出来。

最简单的方式， 你试着删除这个  1 ﾠ   就会发现要删两次。

**Comment by zaqwsxcderfvtgb** [comment]
刚才可以打印出来了，也就是说这个a是前后加空格代表的字符集组成的变量,但是现在不报错，只是打印出来的是false，
`var a = 1;
var ﾠ1 = a;
var ﾠ2 = a;
var ﾠ3 = a;  console.log(aﾠ ==1 && a == 2 && ﾠa ==3)`
VM246:4 false

**Comment by hooper-hc** [comment]
> 刚才可以打印出来了，也就是说这个a是前后加空格代表的字符集组成的变量,但是现在不报错，只是打印出来的是false，
> `var a = 1; var ﾠ1 = a; var ﾠ2 = a; var ﾠ3 = a; console.log(aﾠ ==1 && a == 2 && ﾠa ==3)`
> VM246:4 false

@zaqwsxcderfvtgb 这是你敲的么 ？ 逻辑是不对的， 这种思路下，假设特殊字符是 * ,你的代码应该这么写：

```js
var a = 10;
var *1 = a;
var *2 = a;
var *3 = a;
console.log(a == *1 && a == *2 && a == *3 )
```

你声明没问题，但是 console.log 中的123是普通的123， 肯定 false 啊

----

你从原文中赋值代码出来 跑一下，我试了没问题
```js
var  a = 1;
var ﾠ1 = a;
var ﾠ2 = a;
var ﾠ3 = a;
console.log( a ==ﾠ1 && a ==ﾠ2 && a ==ﾠ3 );
```

**Comment by hooper-hc** [comment]
> > 刚才可以打印出来了，也就是说这个a是前后加空格代表的字符集组成的变量,但是现在不报错，只是打印出来的是false，
> > `var a = 1; var ﾠ1 = a; var ﾠ2 = a; var ﾠ3 = a; console.log(aﾠ ==1 && a == 2 && ﾠa ==3)`
> > VM246:4 false
> 
> @zaqwsxcderfvtgb 这是你敲的么 ？ 逻辑是不对的， 这种思路下，假设特殊字符是 * ,你的代码应该这么写：
> 
> ```js
> var a = 10;
> var *1 = a;
> var *2 = a;
> var *3 = a;
> console.log(a == *1 && a == *2 && a == *3 )
> ```
> 
> 你声明没问题，但是 console.log 中的123是普通的123， 肯定 false 啊
> 
> 你从原文中复制代码出来 跑一下，是没问题的
> 
> ```js
> var  a = 1;
> var ﾠ1 = a;
> var ﾠ2 = a;
> var ﾠ3 = a;
> console.log( a ==ﾠ1 && a ==ﾠ2 && a ==ﾠ3 );
> ```

![image](https://user-images.githubusercontent.com/11420374/49927145-48b58400-fef8-11e8-8a7b-c70575e0aece.png)

**Comment by hooper-hc** [comment]
> 试过了，是可以的。
> 感谢不吝赐教，学习了。
> 持续关注

客气了，我还怕表达的不清楚呢，感谢提 issue
