### ISSUE TITLE
趣味模块倒数三条内容 404

### ISSUE THREAD

**Issue by zaqwsxcderfvtgb** [HCThink/h-blog#8]
**bug 描述 / Describe the bug**
趣味模块倒数三条内容 404

**Comment by hooper-hc** [comment]
> **bug 描述 / Describe the bug**
> 趣味模块倒数三条内容 404

--- 

@zaqwsxcderfvtgb  非常感谢阅读和提的 ISSUE，这些对我意义重大！

此问题应该是出自此篇博客首页： https://github.com/HCThink/h-blog

---

感谢@陶嫒 同学的建议： 目录层次过深，阅读起来不方便。

所以 昨天对首页做了改版，将冗余的分类去掉，将很多二级页面提升到一级，方便阅读。结果将部分页面的链接更新到错误的地方

@zaqwsxcderfvtgb 感谢指正， 目前发现的错误链接共有如下几处： 

1. 巧用异步事件队列
2. n 道 JavaScript 难题
3. JS 中经常使用的小技巧，更简短的实现(长期更新)

已经恢复。十分感谢
